otelDemoPostgres:
  enabled: false
  helm:
    global:
      storageClass: "gp2"
      postgresql:
        auth:
          ## @param auth.username Name for a custom user to create
          ##
          username: "ffs"
          ## @param auth.password Password for the custom user to create. Ignored if `auth.existingSecret` is provided
          ##
          password: "ffs"
          ## @param auth.database Name for a custom database to create
          ##
          database: "ffs"
          ## @param auth.enablePostgresUser Assign a password to the "postgres" admin user. Otherwise, remote access will be blocked for this user
          ##
          enablePostgresUser: true
          ## @param auth.postgresPassword Password for the "postgres" admin user. Ignored if `auth.existingSecret` is provided
          ##
          postgresPassword: "postgres"

otelDemo:
  enabled: true
