otelDemoPostgres:
  enabled: true
  helm:
    global:
      storageClass: "gp2"
      postgresql:
        auth:
          username: "ffs"
          password: "ffs"
          database: "ffs"

otelDemo:
  enabled: true
