opentelemetryCollectorDeployment:
  enabled: true
dash0Operator:
  enabled: false
  dash0Export:
    enabled: false
    endpoint: ingress.eu-west-1.aws.dash0.com:4317
    name: dash0-authorization-secret
    apiEndpoint: https://api.eu-west-1.aws.dash0.com
