apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: app-cluster
  region: eu-west-1
  version: "1.31"

kubernetesNetworkConfig:
  ipFamily: IPv4 # or IPv6

managedNodeGroups:
  - name: worker-nodes
    instanceType: t4g.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        ebs: true
        externalDNS: true
        certManager: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver

iam:
  withOIDC: true
