{{- if .Values.dash0Operator.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dash0-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dash0-system
    name: in-cluster
  project: default
  syncPolicy:
    automated:
{{- if .Values.dash0Operator.autoSync }}
      selfHeal: true
{{- end }}
{{- if .Values.dash0Operator.prune }}
      prune: true
{{- end }}
    syncOptions:
      - CreateNamespace=true
  source:
    chart: dash0-operator
    repoURL: https://dash0hq.github.io/dash0-operator
    targetRevision: {{ .Values.dash0Operator.version }}
    helm:
      values: |
        # configuration section for the Dash0 Kubernetes Operator
        operator:
          {{- if .Values.dash0Operator.dash0Export.enabled }}
          dash0Export:
            enabled: {{ .Values.dash0Operator.dash0Export.enabled }}
            endpoint: {{ .Values.dash0Operator.dash0Export.endpoint }}
            name: {{ .Values.dash0Operator.dash0Export.name }}
            token: {{ .Values.dash0Token }}
          {{- end }}
---
# Additional RBAC permissions required for running opentelemetry-collector in daemonset mode
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dash0-operator-opentelemetry-collector-additional
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dash0-operator-opentelemetry-collector-additional
subjects:
  - kind: ServiceAccount
    name: dash0-operator-opentelemetry-collector
    namespace: dash0-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dash0-operator-opentelemetry-collector-additional
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - endpoints
      - services
    verbs:
      - get
      - watch
      - list

  # Required for kubeletstats receiver
  - apiGroups: [""]
    resources: ["nodes/stats"]
    verbs: ["get"]
  # Only needed if you are using extra_metadata_labels or
  # are collecting the request/limit utilization metrics
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  # Required for kubeletstats receiver to retrieve metrics from persistentvolumes, ...
  # https://github.com/honeycombio/field-utils/blob/main/collector-configs/k8s-metrics/03-clusterrole.yaml
  - apiGroups:
      - ""
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - nodes/stats
      - nodes/proxy
      - persistentvolumes
      - persistentvolumeclaims
      - pods
      - pods/status
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
---
{{- end }}